export const ALERT_OPEN_SELECT = "ALERT_OPEN_SELECT";
export const ALERT_CLOSE_SELECT = "ALERT_CLOSE_SELECT";
export const ALERT_OPEN_FAIL_PASSWORD = "ALERT_OPEN_FAIL_PASSWORD";


export const BACKDROP_LOADING_OPEN = "BACKDROP_LOADING_OPEN";
export const BACKDROP_LOADING_COLSE = "BACKDROP_LOADING_COLSE";
